/**
 * A single rectangular region within a redaction
 */
export interface RedactionPart {
  x: number
  y: number
  width: number
  height: number
}

/**
 * A legal rule or justification for redacting content
 */
export interface RedactionRule {
  group?: string
  title: string
  reference?: string
  reason?: string
  full_text?: string
  url?: string
}

/**
 * A redaction annotation on a PDF document
 */
export interface Redaction {
  id: string
  pageIndex: number
  parts: RedactionPart[]
  rule?: RedactionRule
  shouldApply?: boolean
  reason?: string
  isAutoGenerated?: boolean
  isIndeterminate?: boolean
}

/**
 * Options for exporting a redacted PDF
 */
export interface ExportOptions {
  applyRedactions: boolean
}

/**
 * Internal page data structure
 */
export interface PageData {
  image: string
  bounds: [number, number, number, number]
  content: any
  lines: any[]
  words: WordData[]
}

/**
 * Word data from PDF text extraction
 */
export interface WordData {
  text: string
  bbox: {
    x0: number
    y0: number
    x1: number
    y1: number
  }
}

/**
 * Bounding box coordinates
 */
export interface BoundingBox {
  x0: number
  y0: number
  x1: number
  y1: number
}

/**
 * Highlight in progress (during drawing)
 */
export interface HighlightInProgress {
  pageIndex: number
  type: 'freehand' | 'text'
  startX: number
  startY: number
  endX: number
  endY: number
  startWord: WordData | null
  endWord: WordData | null
}

// ============ Component Props ============

/**
 * Props for the controlled PdfRedactor component
 */
export interface PdfRedactorProps {
  /** The PDF file to display */
  file: File
  /** Array of redactions to display */
  redactions: Redaction[]
  /** Available redaction rules */
  rules?: RedactionRule[]
  /** Currently selected redaction ID */
  selectedId?: string | null
  /** Zoom level (percentage, default 100) */
  zoom?: number

  // Required callbacks
  /** Called when a new redaction is added */
  onRedactionAdd: (redaction: Redaction) => void
  /** Called when a redaction is removed */
  onRedactionRemove: (id: string) => void
  /** Called when a redaction is updated */
  onRedactionUpdate: (id: string, updates: Partial<Redaction>) => void
  /** Called when export is requested */
  onExport: (blob: Blob, applied: boolean) => void

  // Optional callbacks
  /** Called when selection changes */
  onSelectionChange?: (id: string | null) => void
  /** Called when zoom changes */
  onZoomChange?: (zoom: number) => void
  /** Called when page text is extracted (for AI integration) */
  onPageTextExtracted?: (text: string, pageIndex: number) => void
}

/**
 * Props for the standalone PdfRedactor component with internal state
 */
export interface PdfRedactorStandaloneProps {
  /** Optional file - component has built-in uploader if not provided */
  file?: File
  /** Available redaction rules */
  rules?: RedactionRule[]
  /** Initial redactions to load */
  initialRedactions?: Redaction[]

  // AI integration (optional)
  /** AI-generated redaction suggestions to merge into the list */
  aiSuggestions?: Redaction[]
  /** Called when page text is extracted - use this to send text to AI */
  onPageTextExtracted?: (text: string, pageIndex: number) => void

  // Events
  /** Called whenever redactions change */
  onRedactionsChange?: (redactions: Redaction[]) => void
  /** Called when export is requested */
  onExport?: (blob: Blob, redactions: Redaction[]) => void
  /** Called when a file is selected (when using built-in uploader) */
  onFileSelect?: (file: File) => void

  // Customization
  /** Label for the upload area */
  uploadLabel?: string
  /** Label for the upload button */
  uploadButtonLabel?: string
}

